[package]
name = "gtk-rs-examples"
version = "0.0.1"
authors = ["The Gtk-rs Project Developers"]

[dependencies]
glib = "^0"
gdk = "^0"
gdk-pixbuf = "^0"
gtk = "^0"
cairo-rs = "^0"

[features]
#default = ["gtk_3_20"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools

[[bin]]
name = "basic"

[[bin]]
name = "builder_basics"

[[bin]]
name = "cairotest"

[[bin]]
name = "cairo_threads"

[[bin]]
name = "grid"

[[bin]]
name = "gtktest"

[[bin]]
name = "notebook"

[[bin]]
name = "sync_widgets"

[[bin]]
name = "text_viewer"

[[bin]]
name = "treeview"

[[bin]]
name = "multithreading_context"

[[bin]]
name = "simple_treeview"

[[bin]]
name = "menu_bar"

[replace]
"gtk:0.1.2" = { git = 'https://github.com/EPashkin/gtk' }
"gdk:0.5.2" = { git = 'https://github.com/EPashkin/gdk' }
"gdk-pixbuf:0.1.2" = { git = 'https://github.com/EPashkin/gdk-pixbuf' }
"pango:0.1.2" = { git = 'https://github.com/EPashkin/pango' }
"cairo-rs:0.1.2" = { git = 'https://github.com/EPashkin/cairo' }
"cairo-sys-rs:0.3.3" = { git = 'https://github.com/EPashkin/cairo' }
"gio:0.1.2" = { git = 'https://github.com/EPashkin/gio' }
"glib:0.1.2" = { git = 'https://github.com/EPashkin/glib' }
"atk-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"gdk-pixbuf-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"gdk-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"gio-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"glib-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"gobject-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"gtk-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
"pango-sys:0.3.3" = { git = 'https://github.com/EPashkin/rust-gnome-sys' }
