[package]
name = "glib"
version = "0.0.3"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the GLib library"
repository = "https://github.com/rust-gnome/glib"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rust-gnome/glib"
documentation = "https://github.com/rust-gnome/glib"

keywords = ["glib", "gtk", "gnome", "GUI"]

[lib]
name = "glib"

[dependencies]
gio-sys = { git = "https://github.com/rust-gnome/sys" }
glib-sys = { git = "https://github.com/rust-gnome/sys" }
gobject-sys = { git = "https://github.com/rust-gnome/sys" }
libc = "0.1"
