[package]
name = "gio"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["glib", "gio", "gtk-rs", "gnome"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gio/"
version = "0.3.0"
description = "Rust bindings for the Gio library"
repository = "https://github.com/gtk-rs/gio"
build = "build.rs"

[lib]
name = "gio"

[features]
v2_46 = ["v2_44", "gio-sys/v2_46"]
v2_34 = ["gio-sys/v2_34"]
v2_42 = ["v2_40", "gio-sys/v2_42"]
v2_44 = ["v2_42", "gio-sys/v2_44"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_38 = ["v2_36", "gio-sys/v2_38"]
v2_50 = ["v2_48", "gio-sys/v2_50"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_48 = ["v2_46", "gio-sys/v2_48"]
v2_36 = ["v2_34", "gio-sys/v2_36"]
v2_40 = ["v2_38", "gio-sys/v2_40"]
dox = ["gio-sys/dox", "glib/dox"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"

[dependencies.gio-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.4.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.gobject-sys]
version = "0.5.0"
git = "https://github.com/gtk-rs/sys"
