[package]
name = "gtk"
version = "0.0.7"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GTK+ library"
repository = "https://github.com/gtk-rs/gtk"
license = "MIT"
homepage = "https://github.com/gtk-rs/gtk"
documentation = "https://github.com/gtk-rs/gtk"

readme = "README.md"

keywords = ["gtk", "gnome", "GUI"]

[lib]
name = "gtk"

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
cairo-sys-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf-sys = { git = "https://github.com/gtk-rs/sys" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
gio-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
gtk-sys = { git = "https://github.com/gtk-rs/sys" }
libc = "0.1"
pango = { git = "https://github.com/gtk-rs/pango" }
pango-sys = { git = "https://github.com/gtk-rs/sys" }
