[package]
name = "gdk-pixbuf"
version = "0.0.1"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GdkPixbuf library"
repository = "https://github.com/gtk-rs/gdk-pixbuf"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gdk_pixbuf/"

keywords = ["gdk-pixbuf", "gtk-rs", "gnome"]

[lib]
name = "gdk_pixbuf"

[features]
"2.28" = ["gdk-pixbuf-sys/2.28"]
"2.30" = ["2.28", "gdk-pixbuf-sys/2.30"]
"2.32" = ["2.30", "gdk-pixbuf-sys/2.32"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.0.1"
optional = true

[dependencies]
libc = "0.2"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.8"
