[package]
name = "gdk"
version = "0.3.0"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the GDK library"
repository = "https://github.com/gtk-rs/gdk"
license = "MIT"
homepage = "https://github.com/gtk-rs/gdk"
documentation = "https://github.com/gtk-rs/gdk"

readme = "README.md"

keywords = ["gdk", "gtk", "gnome", "GUI"]

[lib]
name = "gdk"

[features]
"3.6" = ["gdk-sys/3.6"]
"3.8" = ["3.6", "gdk-sys/3.8", "gdk-pixbuf/2.28", "pango/1.32.4"]
"3.10" = ["3.8", "gdk-sys/3.10", "cairo-rs/1.12"]
"3.12" = ["3.10", "gdk-sys/3.12"]
"3.14" = ["3.12", "gdk-sys/3.14", "gdk-pixbuf/2.30", "pango/1.34"]
"3.16" = ["3.14", "gdk-sys/3.16"]

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/cairo" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gdk-pixbuf" }
gdk-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }
libc = "0.1"
