[package]
name = "pango-cairo"
documentation = "http://gtk-rs.org/docs/pango/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["pango", "cairo", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.2.0"
description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango-cairo"
license = "MIT"

[features]
dox = []

[dependencies]
libc = "0.2"
bitflags = "0.9"

[dependencies.pango-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.glib]
version = "0.3.0"
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.cairo-sys-rs]
version = "0.4.0"
git = "https://github.com/gtk-rs/cairo"

[dependencies.pango-cairo-sys]
version = "0.4.0"
path = "../sys//pango-cairo-sys"

[dependencies.pango]
version = "0.2.0"
git = "https://github.com/gtk-rs/pango"

[dependencies.cairo-rs]
version = "0.2.0"
git = "https://github.com/gtk-rs/cairo"

[patch."https://github.com/gtk-rs/sys"]
glib-sys = { path = "../sys/glib-sys" }
pango-sys = { path = "../sys/pango-sys" }
gobject-sys = { path = "../sys/gobject-sys" }
