[package]
name = "glib"
documentation = "http://gtk-rs.org/docs/glib/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
description = "Rust bindings for the GLib library"
readme = "README.md"
version = "0.3.0"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/glib"
license = "MIT"

[lib]
name = "glib"

[dependencies]
lazy_static = "0.2"
libc = "0.2"
bitflags = "0.9"

[dependencies.glib-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.4.0"
git = "https://github.com/gtk-rs/sys"

[features]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_44 = ["v2_40", "glib-sys/v2_44", "gobject-sys/v2_44"]
v2_40 = ["v2_38", "glib-sys/v2_40"]
v2_50 = ["v2_48", "glib-sys/v2_50"]
v2_38 = ["glib-sys/v2_38", "gobject-sys/v2_38"]