[package]
name = "glib"
version = "0.0.8"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the GLib library"
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gtk-rs/glib"
documentation = "https://github.com/gtk-rs/glib"

keywords = ["glib", "gtk", "gnome", "GUI"]

[lib]
name = "glib"

[dependencies]
libc = "0.2"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"
