[package]
name = "gdk"
version = "0.1.1"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"

description = "Rust bindings for the GDK library"
repository = "https://github.com/rust-gnome/gdk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gdk"
documentation = "https://github.com/rust-gnome/gdk"

readme = "README.md"

keywords = ["gdk", "gtk", "gnome", "GUI"]

[lib]
name = "gdk"

[features]
gdk_3_4 = []
gdk_3_6 = []
gdk_3_8 = []
gdk_3_10 = []
gdk_3_12 = []
gdk_3_14 = []

[dependencies]
cairo-rs = { git = "https://github.com/rust-gnome/cairo" }
gdk-pixbuf-sys = { git = "https://github.com/rust-gnome/sys" }
gdk-sys = { git = "https://github.com/rust-gnome/sys" }
glib = { git = "https://github.com/rust-gnome/glib" }
libc = "0.1"
