[package]
name = "gtk"
version = "0.0.3"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"

description = "Rust bindings for the GTK+ library"
repository = "https://github.com/rust-gnome/gtk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gtk"
documentation = "https://github.com/rust-gnome/gtk"

readme = "README.md"

keywords = ["gtk", "gnome", "GUI"]

[lib]
name = "gtk"

[features]
gtk_3_4 = []
gtk_3_6 = []
gtk_3_8 = []
gtk_3_10 = ["cairo-rs/cairo_1_12"]
gtk_3_12 = ["gtk_3_10"]
gtk_3_14 = ["gtk_3_12"]

[dependencies.gdk-sys]
git = "https://github.com/rust-gnome/gdk"

[dependencies.gdk]
git = "https://github.com/rust-gnome/gdk"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies.pango-sys]
git = "https://github.com/rust-gnome/pango"

[dependencies.pango]
git = "https://github.com/rust-gnome/pango"

[dependencies.cairo-sys-rs]
git = "https://github.com/rust-gnome/cairo"

[dependencies.cairo-rs]
git = "https://github.com/rust-gnome/cairo"

[dependencies.gtk-sys]
path = "gtk-sys"

[dependencies]
libc = "0.1"