[package]
name = "pango"
version = "0.0.1"
authors = ["The Rust-gnome Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/rust-gnome/pango"
license = "MIT"

[lib]
name = "pango"

[dependencies]
libc = "0.1"
c_vec = "^1.0.0"

[dependencies.pango-sys]
path = "pango-sys"
version = "0.1.0"