[package]
name = "cairo-rs"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the Cairo library"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/cairo/"

keywords = ["cairo", "gtk-rs", "gnome", "GUI"]

[lib]
name = "cairo"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
png = ["cairo-sys-rs/png"]
xcb = ["cairo-sys-rs/xcb"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v1_12 = ["cairo-sys-rs/v1_12"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "^0.1.1"
optional = true

[dependencies]
libc = "0.2"
c_vec = "~1.2"
cairo-sys-rs = "^0.3.3"
glib = "^0.1.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.7"
