[package]
name = "pango"
version = "0.0.7"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango"
license = "MIT"
homepage = "https://github.com/gtk-rs/pango"
documentation = "https://github.com/gtk-rs/pango"

readme = "README.md"

keywords = ["pango", "gtk", "gnome"]

[lib]
name = "pango"

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
libc = "0.1"
pango-sys  = { git = "https://github.com/gtk-rs/sys" }
