[package]
name = "cairo"
version = "0.0.1"
authors = ["guillaume1.gomez@gmail.com", "letang.jeremy@gmail.com", "mathijs.henquet@gmail.com", "bpgarman@fastmail.fm", "me@bstr.eu", "zsoakes@gmail.com"]

description = "A rust binding for the cairo library"
repository = "https://github.com/rust-gnome/cairo"
license = "LGPL-3.0+"

[dependencies]
libc = "0.1"
c_vec = "^1.0.0"

[lib]
name = "cairo"
crate_type = ["rlib"]
path = "src/cairo.rs"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib.git"


[dependencies.cairo-sys]
path = "cairo-sys"
version = "0.1.0"