[package]
name = "gtk"
version = "0.0.3"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"

description = "Rust bindings for the GTK+ library"
repository = "https://github.com/rust-gnome/gtk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gtk"
documentation = "https://github.com/rust-gnome/gtk"

readme = "README.md"

keywords = ["gtk", "gnome", "GUI"]

[lib]
name = "gtk"

[dependencies.gtk-sys]
path = "gtk-sys"

[dependencies]
cairo-rs = { git = "https://github.com/rust-gnome/cairo" }
cairo-sys-rs = { git = "https://github.com/rust-gnome/cairo" }
gdk-pixbuf-sys = { git = "https://github.com/rust-gnome/sys" }
gdk = { git = "https://github.com/rust-gnome/gdk" }
gdk-sys = { git = "https://github.com/rust-gnome/sys" }
gio-sys = { git = "https://github.com/rust-gnome/sys" }
glib = { git = "https://github.com/rust-gnome/glib" }
glib-sys = { git = "https://github.com/rust-gnome/sys" }
gobject-sys = { git = "https://github.com/rust-gnome/sys" }
libc = "0.1"
pango = { git = "https://github.com/rust-gnome/pango" }
pango-sys = { git = "https://github.com/rust-gnome/sys" }
