[package]
name = "cairo-rs"
version = "0.0.4"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"

description = "Rust bindings for the Cairo library"
repository = "https://github.com/rust-gnome/cairo"
license = "MIT"
homepage = "https://github.com/rust-gnome/cairo"
documentation = "https://github.com/rust-gnome/cairo"

readme = "README.md"

keywords = ["cairo", "gtk", "gnome", "GUI"]

[lib]
name = "cairo"

[features]
cairo_1_10 = []
cairo_1_12 = []

[dependencies.cairo-sys-rs]
path = "./cairo-sys-rs"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies]
libc = "0.1"
c_vec = "~1.0"
