[package]
name = "pango"
version = "0.0.7"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/pango/"

keywords = ["pango", "gtk-rs", "gnome"]

[features]
"1.31" = ["pango-sys/1.31"]
"1.32" = ["1.31", "pango-sys/1.32"]
"1.32.4" = ["1.32", "pango-sys/1.32.4"]
"1.34" = ["1.32.4", "pango-sys/1.34"]

[dependencies]
libc = "0.2"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.8"
