[package]
name = "pango"
version = "0.0.3"
authors = ["The Rust-GNOME Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/rust-gnome/pango"
license = "MIT"
homepage = "https://github.com/rust-gnome/pango"
documentation = "https://github.com/rust-gnome/pango"

readme = "README.md"

keywords = ["pango", "gtk", "gnome"]

[lib]
name = "pango"

[dependencies]
glib = { git = "https://github.com/rust-gnome/glib" }
libc = "0.1"
pango-sys  = { git = "https://github.com/rust-gnome/sys" }
