[package]
name = "glib"
version = "0.0.2"
authors = ["The Rust-GNOME Project Developers"]

description = "Rust bindings for the GLib library"
repository = "https://github.com/rust-gnome/glib"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rust-gnome/glib"
documentation = "https://github.com/rust-gnome/glib"

keywords = ["glib", "gtk", "gnome", "GUI"]

[lib]
name = "glib"

[dependencies]
libc = "0.1"
glib-sys = "^0"
