[package]
name = "gdk"
version = "0.0.1"
authors = ["guillaume1.gomez@gmail.com"]

description = "A rust binding for the GDK library"
repository = "https://github.com/rust-gnome/gdk"
license = "MIT"

[dependencies]
libc = "0.1"
c_vec = "^1.0.0"

[lib]
name = "gdk"
crate_type = ["rlib"]
path = "src/gdk.rs"

[dependencies.gdk3-sys]
path = "gdk3-sys"
version = "0.1.0"

[dependencies.glib]
git = "https://github.com/rust-gnome/glib.git"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib.git"