[package]
name = "glib"
documentation = "http://gtk-rs.org/docs/glib/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
description = "Rust bindings for the GLib library"
readme = "README.md"
version = "0.5.0"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/glib", service = "github" }
travis-ci = { repository = "gtk-rs/glib" }

[lib]
name = "glib"

[dependencies]
lazy_static = "1.0"
libc = "0.2"
bitflags = "1.0"
futures-core-preview = { version = "0.2", optional = true }
futures-executor-preview = { version = "0.2", optional = true }
futures-channel-preview = { version = "0.2", optional = true }
futures-util-preview = { version = "0.2", optional = true }
futures-stable-preview = { version = "0.2", optional = true }

[dependencies.glib-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
version = "0.6.0"
git = "https://github.com/gtk-rs/sys"

[dev-dependencies]
tempdir = "0.3"

[features]
v2_34 = ["glib-sys/v2_34", "gobject-sys/v2_34"]
v2_36 = ["v2_34", "glib-sys/v2_36", "gobject-sys/v2_36"]
v2_38 = ["v2_36", "glib-sys/v2_38", "gobject-sys/v2_38"]
v2_40 = ["v2_38", "glib-sys/v2_40"]
v2_44 = ["v2_40", "glib-sys/v2_44", "gobject-sys/v2_44"]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_50 = ["v2_48", "glib-sys/v2_50"]
v2_52 = ["v2_50", "glib-sys/v2_52"]
v2_54 = ["v2_52", "glib-sys/v2_54", "gobject-sys/v2_54"]
futures = ["futures-core-preview", "futures-executor-preview", "futures-channel-preview", "futures-util-preview", "v2_36"]
futures-nightly = ["futures", "futures-core-preview/nightly", "futures-stable-preview", "futures-stable-preview/nightly"]
dox = ["glib-sys/dox", "gobject-sys/dox"]
