[package]
name = "rgtk-examples"
version = "0.0.1"
authors = ["The Rust-gnome Project Developers"]

[dependencies]
libc = "0.1"
glib = "^0"
gdk = "^0"
gtk = "^0"
cairo-rs = "^0"

[features]
gtk_3_10 = ["gtk/gtk_3_10"]
gtk_3_14 = ["gtk/gtk_3_14", "gtk_3_10"]

[[bin]]
name = "basic"

[[bin]]
name = "cairotest"

[[bin]]
name = "gtktest"

[[bin]]
name = "notebook"

[[bin]]
name = "sync_widgets"

[[bin]]
name = "text_viewer"

[[bin]]
name = "treeview"

[[bin]]
name = "builder_basics"
