[package]
name = "cairo-rs"
version = "0.0.8"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the Cairo library"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "https://github.com/gtk-rs/cairo"
documentation = "https://github.com/gtk-rs/cairo"

readme = "README.md"

keywords = ["cairo", "gtk", "gnome", "GUI"]

[lib]
name = "cairo"

[features]
"1.12" = ["cairo-sys-rs/1.12"]

[dependencies.cairo-sys-rs]
path = "./cairo-sys-rs"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies]
libc = "0.1"
c_vec = "~1.0"
