[package]
name = "gtk"
version = "0.0.7"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GTK+ library"
repository = "https://github.com/gtk-rs/gtk"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gtk/"

keywords = ["gtk", "gtk-rs", "gnome", "GUI"]

[lib]
name = "gtk"

[features]
"3.6" = ["gtk-sys/3.6", "gdk/3.6"]
"3.8" = ["3.6", "gtk-sys/3.8", "gdk/3.8"]
"3.10" = ["3.8", "gtk-sys/3.10", "gdk/3.10"]
"3.12" = ["3.10", "gtk-sys/3.12", "gdk/3.12"]
"3.14" = ["3.12", "gtk-sys/3.14", "gdk/3.14"]
"3.16" = ["3.14", "gtk-sys/3.16", "gdk/3.16"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.0.1"
optional = true

[dependencies]
libc = "0.2"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.3.0"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.0.8"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.8"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
version = "0.3.0"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"
version = "0.0.1"

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"
version = "0.0.7"
