[package]
name = "pango"
version = "0.0.8"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the Pango library"
repository = "https://github.com/gtk-rs/pango"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/pango/"

keywords = ["pango", "gtk-rs", "gnome"]

[features]
v1_31 = ["pango-sys/v1_31"]
v1_32 = ["v1_31", "pango-sys/v1_32"]
v1_32_4 = ["v1_32", "pango-sys/v1_32_4"]
v1_34 = ["v1_32_4", "pango-sys/v1_34"]

[dependencies]
libc = "0.2"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.9"
