[package]
name = "cairo-rs"
version = "0.0.8"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the Cairo library"
repository = "https://github.com/gtk-rs/cairo"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/cairo/"

keywords = ["cairo", "gtk-rs", "gnome", "GUI"]

[lib]
name = "cairo"

[features]
"1.12" = ["cairo-sys-rs/1.12"]
png = ["cairo-sys-rs/png"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
version = "0.0.1"
optional = true

[dependencies.cairo-sys-rs]
path = "cairo-sys-rs"
version = "0.3.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.0.8"

[dependencies]
libc = "0.2"
c_vec = "~1.0"
