[package]
name = "glib"
documentation = "http://gtk-rs.org/docs/glib/"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
description = "Rust bindings for the GLib library"
readme = "README.md"
version = "0.8.0"
keywords = ["glib", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/glib"
license = "MIT"
exclude = [
    "gir-files/*",
]

[badges]
appveyor = { repository = "GuillaumeGomez/glib", service = "github" }
travis-ci = { repository = "gtk-rs/glib" }

[lib]
name = "glib"

[dependencies]
lazy_static = "1.2"
libc = "0.2"
bitflags = "1.0"
futures-core = "0.3"
futures-task = "0.3"
futures-executor = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }

[dev-dependencies]
gio = { git = "https://github.com/gtk-rs/gio" }
gtk = { git = "https://github.com/gtk-rs/gtk" }
tempfile = "3"

[features]
v2_44 = ["glib-sys/v2_44", "gobject-sys/v2_44"]
v2_46 = ["v2_44", "glib-sys/v2_46", "gobject-sys/v2_46"]
v2_48 = ["v2_46", "glib-sys/v2_48"]
v2_50 = ["v2_48", "glib-sys/v2_50"]
v2_52 = ["v2_50", "glib-sys/v2_52"]
v2_54 = ["v2_52", "glib-sys/v2_54", "gobject-sys/v2_54"]
v2_56 = ["v2_54", "glib-sys/v2_56"]
v2_58 = ["v2_56", "glib-sys/v2_58"]
v2_60 = ["v2_58", "glib-sys/v2_60"]
dox = ["glib-sys/dox", "gobject-sys/dox"]

[package.metadata.docs.rs]
features = ["dox"]
