[package]
name = "gio"
version = "0.1.2"
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"

description = "Rust bindings for the GLib library"
repository = "https://github.com/gtk-rs/gio"
license = "MIT"
homepage = "http://gtk-rs.org/"
documentation = "http://gtk-rs.org/docs/gio/"
keywords = ["glib", "gio", "gtk-rs", "gnome"]

[lib]
name = "gio"

[features]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
v2_34 = ["gio-sys/v2_34"]
v2_36 = ["v2_34", "gio-sys/v2_36"]
v2_38 = ["v2_36", "gio-sys/v2_38"]
v2_40 = ["v2_38", "gio-sys/v2_40"]
v2_42 = ["v2_40", "gio-sys/v2_42"]
v2_44 = ["v2_42", "gio-sys/v2_44"]
v2_46 = ["v2_44", "gio-sys/v2_46"]
v2_48 = ["v2_46", "gio-sys/v2_48"]
v2_50 = ["v2_48", "gio-sys/v2_50"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "^0.1.1"
optional = true

[dependencies]
bitflags = "0.5"
libc = "0.2"
gio-sys = "^0.3.3"
glib-sys = "^0.3.3"
glib = "^0.1.2"
gobject-sys = "^0.3.3"
