[package]
name = "gtk"
version = "0.0.1"
authors = ["The Rust-GNOME Project Developers"]

description = "Rust bindings for the GTK+ library"
repository = "https://github.com/rust-gnome/gtk"
license = "MIT"

[lib]
name = "gtk"

[features]
default = ["gtk_3_6", "cairo_1_10"]
gtk_3_4 = ["gtk-sys/gtk_3_4", "gdk/gdk_3_4"]
gtk_3_6 = ["gtk-sys/gtk_3_6", "gdk/gdk_3_6", "gtk_3_4"]
gtk_3_8 = ["gtk-sys/gtk_3_8", "gdk/gdk_3_8", "gtk_3_6"]
gtk_3_10 = ["gtk-sys/gtk_3_10", "gdk/gdk_3_10", "gtk_3_8"]
gtk_3_12 = ["gtk-sys/gtk_3_12", "gdk/gdk_3_12", "gtk_3_10"]
gtk_3_14 = ["gtk-sys/gtk_3_14", "gdk/gdk_3_14", "gtk_3_12"]
cairo_1_10 = ["cairo/cairo_1_10"]
cairo_1_12 = ["cairo/cairo_1_12"]

[dependencies]
libc = "0.1"
c_vec = "^1.0.0"

[dependencies.gtk-sys]
path = "gtk-sys"
version = "0.1.0"

[dependencies.cairo-sys]
git = "https://github.com/rust-gnome/cairo"

[dependencies.cairo]
git = "https://github.com/rust-gnome/cairo"
default-features = false

[dependencies.glib]
git = "https://github.com/rust-gnome/glib"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib"

[dependencies.gdk-sys]
git = "https://github.com/rust-gnome/gdk"

[dependencies.gdk]
git = "https://github.com/rust-gnome/gdk"
default-features = false

[dependencies.pango-sys]
git = "https://github.com/rust-gnome/pango"

[dependencies.pango]
git = "https://github.com/rust-gnome/pango"
