[package]
name = "graphene"
license = "MIT"
homepage = "http://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["graphene", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "http://gtk-rs.org/docs/gdk/"
version = "0.10.0"
description = "Rust bindings for the Graphene library"
repository = "https://github.com/gtk-rs/graphene"
build = "build.rs"
exclude = [
    "gir-files/*",
]

[lib]
name = "graphene"

[features]
v1_2 = ["graphene-sys/v1_2"]
v1_4 = ["v1_2", "graphene-sys/v1_4"]
v1_6 = ["v1_4", "graphene-sys/v1_6"]
dox = ["graphene-sys/dox", "glib/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
lazy_static = "1.0"
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
glib = { git = "https://github.com/gtk-rs/glib" }
graphene-sys = { git = "https://github.com/gtk-rs/sys" }

[dev-dependencies]
gir-format-check = "^0.1"
